# Equipo LatinR 2022 {.unnumbered}

## Chairs LatinR

Las Chairs de LatinR son responsables de la coordinación general de la conferencia. Entre sus tareas se encuentran la definición de la visión y los objetivos del evento, la articulación de los distintos equipos de trabajo, la toma de decisiones estratégicas y el seguimiento y ejecución de las actividades necesarias para garantizar el desarrollo exitoso de la conferencia. Asimismo, promueven los valores de colaboración, diversidad e inclusión que caracterizan a la comunidad LatinR.

| Nombre | País | Institución |
|--------|------|------|
| Natalia da Silva | Uruguay | Universidad de La República, R-Ladies Montevideo |
| Riva Quiroga | Chile | Universidad Católica de Chile, R-Ladies Santiago/Valparaiso |
| Yanina Bellini Saibene | Argentina | Instituto Nacional de Tecnología Agropecuaria, R-Ladies Santa Rosa + Global |


## Comité Organizador

El Comité Organizador acompaña la planificación y ejecución de la conferencia, colaborando en aspectos clave como la comunicación con participantes y ponentes, el mantenimiento del sitio web, la implementación y seguimiento del Código de Conducta, la gestión de los espacios virtuales de interacción y el soporte durante tutoriales, charlas y sesiones del evento. Además, impulsa y coordina actividades complementarias, como paneles y eventos satélite, que enriquecen la experiencia de la comunidad durante LatinR.

| Nombre | País |
|--------|------|
| Patricia Loto | Argentina |
| Andrea Gómez Vargas | Argentina |
| Joselyn Chávez | México |
| Beatriz Milz| Brasil |
| Macarena Quiroga | Argentina |
| Monica Alonso | Argentina |
| Luis D. Verde Arregoitia | México |
| Pamela Pairo | Uruguay |
| Felipe Osorio | Chile |

## Comité Científico

La calidad académica y técnica de LatinR es posible gracias al trabajo del Comité Científico. Sus integrantes evalúan las contribuciones recibidas para la conferencia mediante un proceso de revisión por pares, en el que cada propuesta es revisada por al menos dos personas. Este proceso busca garantizar la relevancia, calidad y diversidad de los contenidos presentados, contribuyendo al intercambio de conocimientos y experiencias dentro de la comunidad de usuarios y desarrolladores de R en América Latina.

| Nombre | Institución |
|--------|------|
|Alejandra Tapia |	Pontificia Universidad Católica de Chile|
|Alejandro Espinosa-Rada	| ETH Zürich |
|Dra. Jennifer Isasi	| Pennsylvania State University |
|Felipe Osorio |	Universidad Técnica Federico Santa María, Chile |
|Francisca Ortiz Ruiz |	Millennium Institute for Care Research (MICARE), Santiago, Chile |
|Francisco Urdinez |	Pontificia Universidad Católica de Chile |
|Germán Rosati |	CONICET/ EIDAES-UNSAM |
|Ileana Frasier |	Instituto de Suelos CIRN-CNIA; CONICET |
|Inés Varas |	Pontificia Universidad Católica de Chile |
|Juan José Goyeneche	| Instituto de Estadística - Facultad de Ciencias Económicas y de Administración - Uruguay |
|Lucía Inés Rodríguez Planes|	Dirección Regional Patagonia Austral, Administración de Parques Nacionales |
|Luis D. Verde Arregoitia |	Instituto de Ecología AC (INECOL), México |
|Marcela Alfaro Córdoba |	University of California, Santa Cruz |
|María José García Zattera | Pontificia Universidad Católica de Chile |
|Marina Cecilia Cock |	CONICET - Universidad Nacional de La Pampa |
|Naim Bro	| Universidad Adolfo Ibáñez|
|Natalia Morandeira |	Instituto de Investigación e Ingeniería Ambiental - Consejo Nacional de Investigaciones Científicas y Técnica - Universidad Nacional de San Martín |
|Pamela E. Pairo |	AFIP- SDG SIT |
|Ricardo Alonso Olea Ortega	| Pontificia Universidad Católica de Chile |
|Sara Acevedo	| Pontificia Universidad Católica de Chile |
|Vianey Leos Barajas |	University of Toronto |
|Virginia García Alonso	| R Ladies Buenos Aires/IBBEA, CONICET-UBA |
|Zulemma Bazurto Blacio	| Universidad de Guayaquil |
|Adriana Gili	| Universidad Nacional de La Pampa, Argentina |
|Ignacio Álvarez-Castro	| Instituto de Estadística (IESTA), UDELAR|
|Juan Cruz Rodríguez | Argentina |


